# Generated by Django 4.1.1 on 2022-10-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_airline_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='aircraft_type',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='airline',
            name='airline_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airline',
            name='punctuality_rate',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='airlines',
            field=models.CharField(max_length=100),
        ),
    ]
