# Generated by Django 4.1.1 on 2022-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_airline_aircraft_type_airline_airline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='price',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
