# Generated by Django 4.1.3 on 2022-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_airline_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_airport', models.CharField(max_length=100)),
                ('destination_airport', models.CharField(max_length=100)),
                ('airlines', models.CharField(max_length=100)),
                ('flight', models.CharField(max_length=100)),
                ('aircraft_type', models.CharField(default='-', max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('punctuality_rate', models.CharField(default='-', max_length=100)),
                ('price', models.CharField(default='-', max_length=10)),
                ('total_price', models.CharField(default='-', max_length=10)),
                ('carbon_choice', models.CharField(default='-', max_length=10)),
            ],
        ),
    ]
