# Generated by Django 4.1.3 on 2022-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
