# Generated by Django 4.1.3 on 2022-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_alter_order_arrival_time_alter_order_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='airlines',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_airport',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='starting_airport',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
