# Generated by Django 4.1.3 on 2022-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0007_alter_order_airlines_alter_order_destination_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
