# Generated by Django 4.1.3 on 2022-11-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0008_alter_order_arrival_time_alter_order_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_bag',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='seat_number',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
