# Generated by Django 4.1.3 on 2022-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0009_order_check_bag_order_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject_age',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subject_gender',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subject_marital',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_bag',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='seat_number',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
