# Generated by Django 4.1.3 on 2022-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0010_order_subject_age_order_subject_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='survery_Q1_a',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q1_b',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q1_c',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q1_d',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q1_e',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
