# Generated by Django 4.1.3 on 2022-12-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0011_order_survery_q1_a_order_survery_q1_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='survery_Q2',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q3_a',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q3_b',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q3_c',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q3_d',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
