# Generated by Django 4.1.3 on 2022-12-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0012_order_survery_q2_order_survery_q3_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='survery_Q4',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
