# Generated by Django 4.1.3 on 2022-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0013_order_survery_q4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='survery_Q4',
            field=models.CharField(max_length=30),
        ),
    ]
