# Generated by Django 4.1.3 on 2022-12-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0015_remove_order_survery_q4_order_survery_q4_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='survery_Q4_1',
            new_name='survery_Q4_a',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='survery_Q4_2',
            new_name='survery_Q4_b',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='survery_Q4_3',
            new_name='survery_Q4_c',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='survery_Q4_4',
            new_name='survery_Q4_d',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='survery_Q4_5',
            new_name='survery_Q4_e',
        ),
    ]
