# Generated by Django 4.1.3 on 2022-12-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0016_rename_survery_q4_1_order_survery_q4_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='survery_Q5_a',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q5_b',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q5_c',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q5_d',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q5_e',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q5_f',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='survery_Q5_g',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
