# Generated by Django 4.1.3 on 2022-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0017_order_survery_q5_a_order_survery_q5_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='survery_Q6',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
