# Generated by Django 4.1.3 on 2022-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0018_order_survery_q6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='survery_Q6',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
    ]
